-- Mostly written by Claude and manually polished
module TarskiUniverse.Constructions.InductiveRecursiveUniverse where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Isomorphism
open import Cubical.Foundations.HLevels
open import Cubical.Foundations.Equiv

open import Cubical.Functions.FunExtEquiv

open import Cubical.Data.Sigma
open import Cubical.Data.Empty
open import Cubical.Data.Unit

open import TarskiUniverse.Base

-- An inductive-recursive universe generated by Unit, Σ, Π and Eq is a Tarski universe
module _ {ℓ : Level} where

  data U : Type ℓ
  El : U → Type ℓ

  data U where
    UnitC : U
    Sig   : (A : U) (B : El A → U) → U
    Pi    : (A : U) (B : El A → U) → U
    EqC   : (A : U) (a b : El A)   → U

  El UnitC       = Unit*
  El (Sig A B)   = Σ[ x ∈ El A ] El (B x)
  El (Pi A B)    = (x : El A) → El (B x)
  El (EqC A a b) = a ≡ b

  isSetElU : (A : U) → isSet (El A)
  isSetElU UnitC       = isSetUnit*
  isSetElU (Sig A B)   = isSetΣ (isSetElU A) (λ x → isSetElU (B x))
  isSetElU (Pi A B)    = isSetΠ (λ x → isSetElU (B x))
  isSetElU (EqC A a b) = isProp→isSet (isSetElU A a b)

  -- `Code x y` is the "no-confusion" reading of `x ≡ y`: it mirrors the shape
  -- of the constructors directly (using the *actual* path types of the
  -- strictly smaller sub-terms, not a re-derived proxy relation), so that
  -- `reflCode` and `decodeC` are trivial and no coherence tower is needed.
  Code : U → U → Type ℓ
  Code UnitC     UnitC        = Unit*
  Code (Sig A B) (Sig A' B')  = Σ[ e ∈ A ≡ A' ] PathP (λ i → El (e i) → U) B B'
  Code (Pi A B)  (Pi A' B')   = Σ[ e ∈ A ≡ A' ] PathP (λ i → El (e i) → U) B B'
  Code (EqC A a b) (EqC A' a' b') =
    Σ[ e ∈ A ≡ A' ] (PathP (λ i → El (e i)) a a') × (PathP (λ i → El (e i)) b b')
  Code _ _ = ⊥*

  decodeC : {x y : U} → Code x y → x ≡ y
  decodeC {UnitC}      {UnitC}         _               = refl
  decodeC {Sig A B}    {Sig A' B'}     (e , bp)     i  = Sig (e i) (bp i)
  decodeC {Pi A B}     {Pi A' B'}      (e , bp)     i  = Pi (e i) (bp i)
  decodeC {EqC A a b}  {EqC A' a' b'}  (e , pa , pb) i = EqC (e i) (pa i) (pb i)
  decodeC {UnitC}      {Sig _ _}       ()
  decodeC {UnitC}      {Pi _ _}        ()
  decodeC {UnitC}      {EqC _ _ _}     ()
  decodeC {Sig _ _}    {UnitC}         ()
  decodeC {Sig _ _}    {Pi _ _}        ()
  decodeC {Sig _ _}    {EqC _ _ _}     ()
  decodeC {Pi _ _}     {UnitC}         ()
  decodeC {Pi _ _}     {Sig _ _}       ()
  decodeC {Pi _ _}     {EqC _ _ _}     ()
  decodeC {EqC _ _ _}  {UnitC}         ()
  decodeC {EqC _ _ _}  {Sig _ _}       ()
  decodeC {EqC _ _ _}  {Pi _ _}        ()

  reflCode : (x : U) → Code x x
  reflCode UnitC        = tt*
  reflCode (Sig A B)   = refl , refl
  reflCode (Pi A B)    = refl , refl
  reflCode (EqC A a b) = refl , refl , refl

  encodeC : {x y : U} → x ≡ y → Code x y
  encodeC {x} = J (λ y _ → Code x y) (reflCode x)

  decodeC-reflCode : (x : U) → decodeC (reflCode x) ≡ refl
  decodeC-reflCode UnitC        = refl
  decodeC-reflCode (Sig A B)   = refl
  decodeC-reflCode (Pi A B)    = refl
  decodeC-reflCode (EqC A a b) = refl

  decodeEncode : {x y : U} (p : x ≡ y) → decodeC (encodeC p) ≡ p
  decodeEncode {x} =
    J (λ y p → decodeC (encodeC p) ≡ p)
      (cong decodeC (JRefl (λ y _ → Code x y) (reflCode x)) ∙ decodeC-reflCode x)

  isPropCode : (x y : U) → isProp (Code x y)
  isPropId   : (x y : U) → isProp (x ≡ y)
  isPropPathPBody : (A : U) (B : El A → U) (A' : U) (B' : El A' → U)
                    (e : A ≡ A') → isProp (PathP (λ i → El (e i) → U) B B')

  isPropId x y = isPropRetract encodeC decodeC decodeEncode (isPropCode x y)

  isPropPathPBody A B A' B' e =
    isOfHLevelRespectEquiv 1 funExtDepEquiv
      (isPropImplicitΠ λ x0 → isPropImplicitΠ λ x1 → isPropΠ λ _ → isPropId (B x0) (B' x1))

  isPropCode UnitC     UnitC  = isPropUnit*
  isPropCode (Sig A B) (Sig A' B') =
    isPropΣ (isPropId A A') (λ e → isPropPathPBody A B A' B' e)
  isPropCode (Pi A B) (Pi A' B') =
    isPropΣ (isPropId A A') (λ e → isPropPathPBody A B A' B' e)
  isPropCode (EqC A a b) (EqC A' a' b') =
    isPropΣ (isPropId A A') (λ e →
      isProp× (isOfHLevelPathP' 1 (isSetElU A') a a')
              (isOfHLevelPathP' 1 (isSetElU A') b b'))
  isPropCode UnitC       (Sig _ _)    = isProp⊥*
  isPropCode UnitC       (Pi _ _)     = isProp⊥*
  isPropCode UnitC       (EqC _ _ _)  = isProp⊥*
  isPropCode (Sig _ _)   UnitC        = isProp⊥*
  isPropCode (Sig _ _)   (Pi _ _)     = isProp⊥*
  isPropCode (Sig _ _)   (EqC _ _ _)  = isProp⊥*
  isPropCode (Pi _ _)    UnitC        = isProp⊥*
  isPropCode (Pi _ _)    (Sig _ _)    = isProp⊥*
  isPropCode (Pi _ _)    (EqC _ _ _)  = isProp⊥*
  isPropCode (EqC _ _ _) UnitC        = isProp⊥*
  isPropCode (EqC _ _ _) (Sig _ _)    = isProp⊥*
  isPropCode (EqC _ _ _) (Pi _ _)     = isProp⊥*

  isSetU : isSet U
  isSetU = isPropId

  IR_Universe-Base : TarskiUniverse-Base ℓ ℓ
  IR_Universe-Base .TarskiUniverse-Base.U       = U
  IR_Universe-Base .TarskiUniverse-Base.isSetU  = isSetU
  IR_Universe-Base .TarskiUniverse-Base.El      = El
  IR_Universe-Base .TarskiUniverse-Base.isSetEl = isSetElU

  IR_Universe-Sig : TarskiUniverse-Sig IR_Universe-Base
  IR_Universe-Sig .TarskiUniverse-Sig.Sig             = Sig
  IR_Universe-Sig .TarskiUniverse-Sig.SigIso A B      = idIso

  IR_Universe-Pi : TarskiUniverse-Pi IR_Universe-Base
  IR_Universe-Pi .TarskiUniverse-Pi.Pi           = Pi
  IR_Universe-Pi .TarskiUniverse-Pi.PiIso A B    = idIso

  IR_Universe-Unit : TarskiUniverse-Unit IR_Universe-Base
  IR_Universe-Unit .TarskiUniverse-Unit.Unit          = UnitC
  IR_Universe-Unit .TarskiUniverse-Unit.isContrElUnit = isContrUnit*

  IR_Universe-Eq : TarskiUniverse-Eq IR_Universe-Base
  IR_Universe-Eq .TarskiUniverse-Eq.Eq          = EqC
  IR_Universe-Eq .TarskiUniverse-Eq.EqIso A a b = idIso

  IR_Universe-TarskiUniverse : TarskiUniverse ℓ ℓ
  IR_Universe-TarskiUniverse .TarskiUniverse.TU-Base = IR_Universe-Base
  IR_Universe-TarskiUniverse .TarskiUniverse.TU-Unit = IR_Universe-Unit
  IR_Universe-TarskiUniverse .TarskiUniverse.TU-Sig  = IR_Universe-Sig
