module TarskiUniverse.Instances.InductiveRecursiveUniverse where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Isomorphism

open import Cubical.Data.Unit

open import TarskiUniverse.Base
open import Utils.InductiveRecursiveUniverse

-- An inductive-recursive universe generated by Unit, Σ, Π and Eq is a Tarski universe
module _ {ℓ : Level} where

  BareTarskiUniverseU : BareTarskiUniverse ℓ U
  BareTarskiUniverseU .BareTarskiUniverse.isSetU  = isSetU
  BareTarskiUniverseU .BareTarskiUniverse.El      = El
  BareTarskiUniverseU .BareTarskiUniverse.isSetEl = isSetElU

  hasSigmaU : hasSigma BareTarskiUniverseU
  hasSigmaU .hasSigma.Sigma             = Sig
  hasSigmaU .hasSigma.SigmaIso A B      = idIso

  hasPiU : hasPi BareTarskiUniverseU
  hasPiU .hasPi.Pi           = Pi
  hasPiU .hasPi.PiIso A B    = idIso

  hasUnitU : hasUnit BareTarskiUniverseU
  hasUnitU .hasUnit.Unit          = UnitC
  hasUnitU .hasUnit.isContrElUnit = isContrUnit*

  hasEqU : hasEq BareTarskiUniverseU
  hasEqU .hasEq.Eq          = EqC
  hasEqU .hasEq.EqIso A a b = idIso

  TarskiUniverseU : TarskiUniverse ℓ U
  TarskiUniverseU .TarskiUniverse.TU = BareTarskiUniverseU
  TarskiUniverseU .TarskiUniverse.hasUnitTU = hasUnitU
  TarskiUniverseU .TarskiUniverse.hasSigmaTU  = hasSigmaU
